import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { initiateCheckout } from "../lib/payments";
import products from "../products.json";

interface IProduct {
  id: string;
  quantity: number;
}
type TCart = {
  products: {
    [id: string]: IProduct;
  };
};

const defaultCart = {
  products: {},
} as TCart;

export default function Home() {
  const [cart, updateCart] = useState(defaultCart);

  const cartItems =
    cart.products &&
    Object.keys(cart.products).map((key) => {
      // Find the product data in products.json
      const product = products.find(({ id }) => id === key);
      return {
        ...cart.products[key],
        pricePerItem: parseInt(product!.price),
      };
    });
  const subtotal = cartItems.reduce(
    (acc, cur) => acc + cur!.pricePerItem * cur!.quantity,
    0
  );

  const totalItems = cartItems.reduce((acc, cur) => acc + cur!.quantity, 0);

  function checkout() {
    initiateCheckout({
      lineItems: cartItems.map((item) => ({
        price: item.id,
        quantity: item.quantity,
      })),
    });
  }

  function addCart({ id } = { id: "" }) {
    updateCart((prev) => {
      let cart = { ...prev };

      if (cart.products[id]) {
        cart.products[id].quantity += 1;
      } else {
        cart.products[id] = {
          id,
          quantity: 1,
        };
      }
      return cart;
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Space Jelly Shop</h1>

        <p className={styles.description}>
          The best space jellyfish swag on the web!
        </p>

        <p className={styles.description}>
          <strong>Itmes:</strong> {totalItems}
          <br />
          <strong>Total Cost:</strong> ${subtotal}
          <br />
          <button
            className={styles.button}
            onClick={() => {
              checkout();
            }}
          >
            Check Out
          </button>
        </p>

        <ul className={styles.grid}>
          {products.map((product) => {
            const { id, title, description, image, price } = product;
            return (
              <li key={id} className={styles.card}>
                <a href="#" className={styles.card}>
                  <img src={image} alt={title} />

                  <h2>{title}</h2>
                  <p>${price}</p>
                  <p>{description}</p>
                </a>
                <p>
                  <button
                    className={styles.button}
                    onClick={() => {
                      addCart({ id });
                    }}
                  >
                    Add to Cart
                  </button>
                </p>
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
